/*********************************************************
Sublime
**********************************************************
Josiah Wilson
August 19,2020
CMSC 255 section 002
*********************************************************/
public class Hello {
	public static void main(String[] args){
		System.out.println("<Josiah Wilson>");
		System.out.println("<Hello.Java>");
		System.out.println("<Lab 1>");
		System.out.println("<2020>");
		System.out.println("<CMSC 255 002>");
		System.out.println();
	}
}